remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 

title: Appccessibility Shox
description: We create apps that improve the accessibility of the web for disabled users & donate all proceeds to the DNRC.
